cache:
  directories:
  - $HOME/.m2
language: java
jdk:
  - oraclejdk7
  - oraclejdk8
email:
  - ben.alex@acegi.com.au
install:
  - mvn -B -Pdeploy -V -Dgpg.skip=true -DskipTests=true -Dcheckstyle.skip=true -Dpmd.skip=true -Dmdep.analyze.skip=true -Dduplicate-finder.skip=true -Dfindbugs.skip=true -Dlicense.skipAddThirdParty=true -Dlicense.skipUpdateProjectLicense=true -Dlicense.skipUpdateLicense=true -Dmaven.javadoc.skip=true install
script:
  - mvn -B -Pdeploy -Dgpg.skip=true -Dlicense.skipAddThirdParty=true -Dlicense.skipUpdateProjectLicense=true -Dlicense.skipUpdateLicense=true verify
after_success:
  - if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then bash <(curl -s https://codecov.io/bash); fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then echo $GPG_KEY | base64 -d | gpg --batch --fast-import -; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then mvn -B -Pdeploy --settings .travis-settings.xml deploy; fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ]; then mvn -B -Pdeploy --settings .travis-settings.xml site-deploy; fi
